### PR TITLE
Exclude “Transfer”-related Tours of Duty

### PR DESCRIPTION
**Pull request by mjoyce91**
Related to #1680

### CODE REVIEW

**Comment by burgwyn** [comment]
PR looks good, just awaiting some data validation before proceeding

**Comment by burgwyn** [comment]
I can confirm that there are 2 transfer values that show up in the on-site dataset.

**Comment by cydneycappello** [comment]
@burgwyn @mjoyce91 Do we know how many positions are tied to the TODs with a Transfer? Robin had said the term "Transfer" was back office speak for 0 R&R. But I wonder if these are positions people would actually want to research or bid on?

**Comment by burgwyn** [comment]
@cydneycappello and @mjoyce91 736/5589 have a Transfer ToD

**Comment by cydneycappello** [comment]
@burgwyn what is 736/5589? Is that a position number?

**Comment by burgwyn** [comment]
@cydneycappello - sorry 736 positions out of the total 5589 positions have a Transfer ToD

**Comment by cydneycappello** [comment]
@burgwyn Thanks for clarifying. I think we may have to revisit this with Chris and Robin. It may need to be in TalentMAP. That's a significant number.

**Comment by mjoyce91** [comment]
No longer needed

**Pull request closed without merging**
